openapi: 3.0.3
info:
  title: Jarvis-PL API
  version: "1.2.0"
servers:
  - url: https://ai.aneuroasystent.pl

paths:
  /health:
    get:
      operationId: health
      summary: Status serwera
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
