openapi: 3.0.3
info:
  title: Jarvis-PL API
  version: "1.2.0"
servers:
  - url: https://ai.aneuroasystent.pl

paths:
  /health:
    get:
      operationId: health
      summary: Status serwera
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /auth/status:
    get:
      operationId: authStatus
      summary: Status autoryzacji Google
      responses:
        "200":
          description: Tekstowy status (refresh_token: TAK/NIE)
          content:
            text/plain:
              schema:
                type: string

  /auth/reset:
    get:
      operationId: authReset
      summary: Wyczyść tokeny i stan webhooka (ADMIN)
      security:
        - AdminToken: []
      responses:
        "200":
          description: Zresetowano
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

components:
  securitySchemes:
    AdminToken:
      type: apiKey
      in: header
      name: x-admin-token
      description: Wymagane dla /auth/reset