name: keepalive

on:
  schedule:
    - cron: "*/5 * * * *"     # co 5 min
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping endpoints (no-cache, follow redirects)
        run: |
          set -e
          TS=$(date +%s)
          echo "Pinging: $BASE_URL/health?ts=$TS"
          curl -fsSL --http1.1 -m 20 -A "keepalive-gha" "$BASE_URL/health?ts=$TS" | head -c 200
          echo
          echo "Pinging: $BASE_URL/?ts=$TS"
          curl -fsSL --http1.1 -m 20 -A "keepalive-gha" "$BASE_URL/?ts=$TS" | head -c 200
          echo
    env:
      BASE_URL: https://ai.aneuroasystent.pl
