name: keepalive

on:
  schedule:
    - cron: "*/5 * * * *"   # co 5 min
  workflow_dispatch: {}      # ręczne odpalenie z zakładki Actions

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Curl /health
        run: |
          set -e
          echo "Pinging: $BASE_URL/health"
          curl -fsS -m 15 -A "keepalive-gha" "$BASE_URL/health" | head -c 200
    env:
      BASE_URL: https://ai.aneuroasystent.pl
