name: keepalive

on:
  schedule:
    - cron: "*/5 * * * *"   # co 5 min
  workflow_dispatch: {}      # ręczne odpalenie z zakładki Actions

permissions:
  contents: read

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Ping endpoints
        run: |
          set -e
          for path in "/health" "/"; do
            echo "Pinging: $BASE_URL$path"
            for i in 1 2 3; do
              if curl -fsS -m 15 -A "keepalive-gha" "$BASE_URL$path" >/dev/null; then
                echo "OK"
                break
              fi
              echo "retry $i..."
              sleep 2
            done
          done
    env:
      BASE_URL: https://ai.aneuroasystent.pl
